export { Hero } from "./Hero/Hero";
export { Services } from "./Services/Services";
export { Hero2 } from "./Hero2/Hero2";
export { SobreNosotros } from "./SobreNosotros/SobreNosotros";
export { Benefits } from "./Benefits/Benefits";
export { Testimonials } from "./Testimonials/Testimonials";
export { Cta } from "./Cta/Cta";
export { Footer } from "./Footer/Footer";
export { Bubble } from "./Bubble/Bubble";